name: meta-analysis-webscraper
channels:
  - conda-forge
dependencies:
  - attrs=21.4.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.0
  - click=8.1.3
  - colorama=0.4.5
  - dill=0.3.5.1
  - filelock=3.7.1
  - Flask=2.1.3
  - Flask-Cors=3.0.10
  - gevent=21.12.0
  - greenlet=1.1.2
  - idna=3.3
  - itsdangerous=2.1.2
  - Jinja2=3.1.2
  - joblib=1.1.0
  - jsonschema=4.7.2
  - MarkupSafe=2.1.1
  - numpy=1.23.1
  - openpyxl=3.0.10
  - pandas=1.4.3
  - pycparser=2.21
  - pyrsistent=0.18.1
  - python-dateutil=2.8.2
  - pytz=2022.1
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - threadpoolctl=3.1.0
  - urllib3=1.26.10
  - Werkzeug=2.1.2
  - xlrd=2.0.1
  - zope.event=4.5.0
  - zope.interface=5.4.0